/**
 * Argument counts for the built-in filters, excluding the piped input.
 *
 * Core arity is checked so that a missing or extra argument fails the way the
 * reference engine fails. Hosted overloads widen an entry here rather than
 * disabling the check, and filters registered by users are never checked.
 */
export type FilterArity = [min: number, max: number]

export const filterSignatures: Record<string, FilterArity> = {
  abs: [0, 0],
  append: [1, 1],
  at_least: [1, 1],
  at_most: [1, 1],
  base64_decode: [0, 0],
  base64_encode: [0, 0],
  base64_url_safe_decode: [0, 0],
  base64_url_safe_encode: [0, 0],
  capitalize: [0, 0],
  ceil: [0, 0],
  compact: [0, 1],
  concat: [1, 1],
  default: [0, 2],
  divided_by: [1, 1],
  downcase: [0, 0],
  escape: [0, 0],
  escape_once: [0, 0],
  find: [1, 2],
  find_index: [1, 2],
  first: [0, 0],
  floor: [0, 0],
  h: [0, 0],
  has: [1, 2],
  join: [0, 1],
  last: [0, 0],
  lstrip: [0, 1],
  map: [1, 1],
  minus: [1, 1],
  modulo: [1, 1],
  newline_to_br: [0, 0],
  plus: [1, 1],
  prepend: [1, 1],
  reject: [1, 2],
  remove: [1, 1],
  remove_first: [1, 1],
  remove_last: [1, 1],
  replace: [1, 2],
  replace_first: [1, 2],
  replace_last: [2, 2],
  reverse: [0, 0],
  rstrip: [0, 1],
  round: [0, 1],
  size: [0, 0],
  slice: [1, 2],
  sort: [0, 1],
  sort_natural: [0, 1],
  split: [1, 1],
  squish: [0, 0],
  strip: [0, 1],
  strip_html: [0, 0],
  strip_newlines: [0, 0],
  sum: [0, 1],
  times: [1, 1],
  truncate: [0, 2],
  truncatewords: [0, 2],
  uniq: [0, 1],
  upcase: [0, 0],
  url_decode: [0, 0],
  url_encode: [0, 0],
  where: [1, 2]
}
