name: Docs
on: [workflow_dispatch, workflow_call]
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
      - name: Build
        run: |
          npm ci
          npm run build:docs
      - name: Publish
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          branch: gh-pages
          folder: docs/public
      - name: Archive npm failure logs
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs